# Generated by Django 4.2.9 on 2024-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('qlpmapp', '0004_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='role',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='role',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='role',
        ),
        migrations.AddField(
            model_name='administrator',
            name='groups',
            field=models.ManyToManyField(related_name='admin_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='groups',
            field=models.ManyToManyField(related_name='doctor_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='groups',
            field=models.ManyToManyField(related_name='nurse_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(related_name='patient_groups', to='auth.group'),
        ),
    ]
