# Generated by Django 4.2.9 on 2024-01-30 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0007_medicine_created_at_medicine_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
