# Generated by Django 4.2.9 on 2024-01-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0008_alter_schedule_schedule_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
