# Generated by Django 4.2.9 on 2024-01-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0010_alter_appointment_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlpmapp.nurse'),
        ),
    ]
