# Generated by Django 4.2.9 on 2024-01-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0012_alter_prescribedmedicine_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='instructions',
            field=models.CharField(default='Drink', max_length=50),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
