# Generated by Django 4.2.9 on 2024-02-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0013_medicine_dosage_medicine_instructions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='dosage',
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage_instructions',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='usage_instructions',
            field=models.CharField(default='', max_length=50),
        ),
    ]
