# Generated by Django 4.2.9 on 2024-02-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0014_remove_prescribedmedicine_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlpmapp.doctor'),
        ),
    ]
