# Generated by Django 4.2.9 on 2024-02-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0015_appointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='diagnosis',
            new_name='conclusion',
        ),
    ]
