# Generated by Django 4.2.9 on 2024-02-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0016_rename_diagnosis_medicalhistory_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='prescribed_medicines',
            field=models.ManyToManyField(related_name='prescribed_medicines', to='qlpmapp.prescribedmedicine'),
        ),
    ]
