# Generated by Django 4.2.9 on 2024-02-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0017_alter_medicalhistory_prescribed_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('quarter', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('patient_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'unique_together': {('month', 'quarter', 'year')},
            },
        ),
    ]
