# Generated by Django 4.2.9 on 2024-02-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0018_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
