# Generated by Django 4.2.9 on 2024-02-24 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0019_remove_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlpmapp.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='isCancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason_cancel',
            field=models.TextField(default=''),
        ),
    ]
