# Generated by Django 4.2.9 on 2024-02-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0020_appointment_doctor_appointment_iscancel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reason_cancel',
            new_name='reason',
        ),
    ]
