# Generated by Django 4.2.9 on 2024-02-27 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0021_rename_reason_cancel_appointment_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='isCancel',
            new_name='examination',
        ),
    ]
