# Generated by Django 4.2.9 on 2024-02-28 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0023_rename_amount_payment_fee_payment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlpmapp.nurse'),
        ),
    ]
