# Generated by Django 4.2.9 on 2024-02-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0024_payment_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
