# Generated by Django 4.2.9 on 2024-02-29 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qlpmapp', '0025_payment_created_at_payment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='qlpmapp.appointment'),
        ),
    ]
